server:
  AppVersion: 1.0.0
  Port: 8080
  Mode: Development
  CookieName: bizhelm_auth
  ReadTimeout: 10s
  WriteTimeout: 10s
  IdleTimeout: 120s

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: info

postgres:
  Host: localhost
  Port: 5432
  User: postgres
  Password: password
  DBName: account_db
  SSLMode: disable

redis:
  RedisAddr: localhost:6379
  RedisPassword:
  RedisDb: 0
  RedisDefaultdb: 0
  MinIdleConns: 200
  PoolSize: 12000
  PoolTimeout: 240
  Password: ""
  DB: 0

cookie:
  Name: bizhelm_auth
  MaxAge: 86400
  Secure: false
  HttpOnly: true

session:
  Name: session-id
  Prefix: api-session
  Expire: 3600

metrics:
  Url: 0.0.0.0:7070
  ServiceName: api

jaeger:
  Host: localhost:6831
  ServiceName: REST_API
  LogSpans: false